# Generated by Django 3.2.4 on 2021-06-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210615_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dueness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2021-06-16'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2021-06-16'),
        ),
    ]
