# Generated by Django 3.2.4 on 2021-06-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2021-06-30'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2021-06-30'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
