# Generated by Django 3.2.4 on 2021-06-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_auto_20210630_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.TextField(blank=True, default='Not Started'),
        ),
    ]
