# Generated by Django 3.2.4 on 2021-07-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_todo_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2021-07-13'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2021-07-13'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.TextField(default='Not Started'),
        ),
    ]
